
// This file has been generated by the GUI designer. Do not modify.
namespace PagedVirtualMemoryVisualizer
{
	public partial class PagedVirtualMemoryVisualizer
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table table5;

		private global::Gtk.Entry entVirtualAddressOffset;

		private global::Gtk.Entry entVirtualAddressVPN;

		private global::Gtk.Label label34;

		private global::Gtk.Label label35;

		private global::Gtk.Label GtkLabel;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.Table table4;

		private global::Gtk.Entry entPhysAddressOffset;

		private global::Gtk.Entry entPhysAddressPFN;

		private global::Gtk.Label label36;

		private global::Gtk.Label label37;

		private global::Gtk.Label GtkLabel2;

		private global::VisualizerComponents.HWireWidget hWireOffset;

		private global::VisualizerComponents.HWireWidget hWireVPN;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.Table table1;

		private global::Gtk.Entry entPageTablePFN;

		private global::Gtk.Entry entPageTablePFN1;

		private global::Gtk.Entry entPageTablePFN2;

		private global::Gtk.Entry entPageTablePFN3;

		private global::Gtk.Entry entPageTableVPN;

		private global::Gtk.Entry entPageTableVPN1;

		private global::Gtk.Entry entPageTableVPN2;

		private global::Gtk.Entry entPageTableVPN3;

		private global::Gtk.Label label25;

		private global::Gtk.Label label26;

		private global::Gtk.Label GtkLabel3;

		private global::VisualizerComponents.VWireWidget vWirePFN;

		private global::VisualizerComponents.HWireWidget hWirePFN1;

		private global::VisualizerComponents.HWireWidget hWirePFN2;

		private global::VisualizerComponents.HWireWidget hWireOffset2;

		private global::VisualizerComponents.VWireWidget vWireVPN;

		private global::VisualizerComponents.HWireWidget hwirewidget1;

		private global::Gtk.Frame frame3;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.Table table2;

		private global::Gtk.Entry entPhysMem;

		private global::Gtk.Entry entPhysMem1;

		private global::Gtk.Entry entPhysMem10;

		private global::Gtk.Entry entPhysMem11;

		private global::Gtk.Entry entPhysMem12;

		private global::Gtk.Entry entPhysMem13;

		private global::Gtk.Entry entPhysMem14;

		private global::Gtk.Entry entPhysMem15;

		private global::Gtk.Entry entPhysMem2;

		private global::Gtk.Entry entPhysMem3;

		private global::Gtk.Entry entPhysMem4;

		private global::Gtk.Entry entPhysMem5;

		private global::Gtk.Entry entPhysMem6;

		private global::Gtk.Entry entPhysMem7;

		private global::Gtk.Entry entPhysMem8;

		private global::Gtk.Entry entPhysMem9;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.Label label29;

		private global::Gtk.Label label30;

		private global::Gtk.Label label31;

		private global::Gtk.Label label32;

		private global::Gtk.Label label33;

		private global::Gtk.Label label38;

		private global::Gtk.Label label4;

		private global::Gtk.Label label40;

		private global::Gtk.Label label41;

		private global::Gtk.Label label42;

		private global::Gtk.Label label43;

		private global::Gtk.Label label44;

		private global::Gtk.Label label45;

		private global::Gtk.Label label46;

		private global::Gtk.Label label47;

		private global::Gtk.Label label48;

		private global::Gtk.Label label49;

		private global::Gtk.Label label5;

		private global::Gtk.Label label50;

		private global::Gtk.Label label51;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label GtkLabel1;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.Entry entMemoryAccessResult;

		private global::Gtk.Label GtkLabel4;

		private global::VisualizerComponents.VWireWidget vWirePhysMemValue;

		private global::VisualizerComponents.HWireWidget hWirePhysMemValue;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget PagedVirtualMemoryVisualizer.PagedVirtualMemoryVisualizer
			global::Stetic.BinContainer.Attach(this);
			this.Name = "PagedVirtualMemoryVisualizer.PagedVirtualMemoryVisualizer";
			// Container child PagedVirtualMemoryVisualizer.PagedVirtualMemoryVisualizer.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.fixed1.Add(this.fixed2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.fixed2]));
			w1.X = 44;
			w1.Y = 270;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.fixed1.Add(this.fixed3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.fixed3]));
			w2.X = 30;
			w2.Y = 272;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.fixed1.Add(this.fixed4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.fixed4]));
			w3.X = 85;
			w3.Y = 137;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.fixed1.Add(this.fixed5);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.fixed5]));
			w4.X = 493;
			w4.Y = 456;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table(((uint)(4)), ((uint)(1)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.entVirtualAddressOffset = new global::Gtk.Entry();
			this.entVirtualAddressOffset.CanFocus = true;
			this.entVirtualAddressOffset.Name = "entVirtualAddressOffset";
			this.entVirtualAddressOffset.IsEditable = false;
			this.entVirtualAddressOffset.InvisibleChar = '●';
			this.table5.Add(this.entVirtualAddressOffset);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5[this.entVirtualAddressOffset]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entVirtualAddressVPN = new global::Gtk.Entry();
			this.entVirtualAddressVPN.CanFocus = true;
			this.entVirtualAddressVPN.Name = "entVirtualAddressVPN";
			this.entVirtualAddressVPN.IsEditable = false;
			this.entVirtualAddressVPN.InvisibleChar = '●';
			this.table5.Add(this.entVirtualAddressVPN);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5[this.entVirtualAddressVPN]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label34 = new global::Gtk.Label();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("VPN (Virtual Page Number)");
			this.table5.Add(this.label34);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5[this.label34]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label35 = new global::Gtk.Label();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("offset");
			this.table5.Add(this.label35);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5[this.label35]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add(this.table5);
			this.frame2.Add(this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Virtual Address</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel;
			this.fixed1.Add(this.frame2);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame2]));
			w11.X = 28;
			w11.Y = 54;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame4 = new global::Gtk.Frame();
			this.frame4.Name = "frame4";
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(4)), ((uint)(1)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.entPhysAddressOffset = new global::Gtk.Entry();
			this.entPhysAddressOffset.CanFocus = true;
			this.entPhysAddressOffset.Name = "entPhysAddressOffset";
			this.entPhysAddressOffset.IsEditable = false;
			this.entPhysAddressOffset.InvisibleChar = '●';
			this.table4.Add(this.entPhysAddressOffset);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4[this.entPhysAddressOffset]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.entPhysAddressPFN = new global::Gtk.Entry();
			this.entPhysAddressPFN.CanFocus = true;
			this.entPhysAddressPFN.Name = "entPhysAddressPFN";
			this.entPhysAddressPFN.IsEditable = false;
			this.entPhysAddressPFN.InvisibleChar = '●';
			this.table4.Add(this.entPhysAddressPFN);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4[this.entPhysAddressPFN]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label36 = new global::Gtk.Label();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString("PFN (Physical Frame Number)");
			this.table4.Add(this.label36);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.label36]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label37 = new global::Gtk.Label();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("offset");
			this.table4.Add(this.label37);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.label37]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add(this.table4);
			this.frame4.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Physical Address</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel2;
			this.fixed1.Add(this.frame4);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame4]));
			w18.X = 400;
			w18.Y = 54;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hWireOffset = new global::VisualizerComponents.HWireWidget();
			this.hWireOffset.WidthRequest = 188;
			this.hWireOffset.HeightRequest = 3;
			this.hWireOffset.Events = ((global::Gdk.EventMask)(256));
			this.hWireOffset.Name = "hWireOffset";
			this.hWireOffset.Identifier = "state0";
			this.fixed1.Add(this.hWireOffset);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hWireOffset]));
			w19.X = 211;
			w19.Y = 154;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hWireVPN = new global::VisualizerComponents.HWireWidget();
			this.hWireVPN.WidthRequest = 92;
			this.hWireVPN.HeightRequest = 3;
			this.hWireVPN.Events = ((global::Gdk.EventMask)(256));
			this.hWireVPN.Name = "hWireVPN";
			this.hWireVPN.Identifier = "state0-0";
			this.fixed1.Add(this.hWireVPN);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hWireVPN]));
			w20.X = 19;
			w20.Y = 311;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame5 = new global::Gtk.Frame();
			this.frame5.Name = "frame5";
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTablePFN = new global::Gtk.Entry();
			this.entPageTablePFN.CanFocus = true;
			this.entPageTablePFN.Name = "entPageTablePFN";
			this.entPageTablePFN.Text = global::Mono.Unix.Catalog.GetString("00");
			this.entPageTablePFN.IsEditable = false;
			this.entPageTablePFN.InvisibleChar = '●';
			this.table1.Add(this.entPageTablePFN);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTablePFN]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTablePFN1 = new global::Gtk.Entry();
			this.entPageTablePFN1.CanFocus = true;
			this.entPageTablePFN1.Name = "entPageTablePFN1";
			this.entPageTablePFN1.IsEditable = false;
			this.entPageTablePFN1.InvisibleChar = '●';
			this.table1.Add(this.entPageTablePFN1);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTablePFN1]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTablePFN2 = new global::Gtk.Entry();
			this.entPageTablePFN2.CanFocus = true;
			this.entPageTablePFN2.Name = "entPageTablePFN2";
			this.entPageTablePFN2.IsEditable = false;
			this.entPageTablePFN2.InvisibleChar = '●';
			this.table1.Add(this.entPageTablePFN2);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTablePFN2]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTablePFN3 = new global::Gtk.Entry();
			this.entPageTablePFN3.CanFocus = true;
			this.entPageTablePFN3.Name = "entPageTablePFN3";
			this.entPageTablePFN3.IsEditable = false;
			this.entPageTablePFN3.InvisibleChar = '●';
			this.table1.Add(this.entPageTablePFN3);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTablePFN3]));
			w24.TopAttach = ((uint)(4));
			w24.BottomAttach = ((uint)(5));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTableVPN = new global::Gtk.Entry();
			this.entPageTableVPN.CanFocus = true;
			this.entPageTableVPN.Name = "entPageTableVPN";
			this.entPageTableVPN.Text = global::Mono.Unix.Catalog.GetString("101");
			this.entPageTableVPN.IsEditable = false;
			this.entPageTableVPN.InvisibleChar = '●';
			this.table1.Add(this.entPageTableVPN);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTableVPN]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTableVPN1 = new global::Gtk.Entry();
			this.entPageTableVPN1.CanFocus = true;
			this.entPageTableVPN1.Name = "entPageTableVPN1";
			this.entPageTableVPN1.IsEditable = false;
			this.entPageTableVPN1.InvisibleChar = '●';
			this.table1.Add(this.entPageTableVPN1);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTableVPN1]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTableVPN2 = new global::Gtk.Entry();
			this.entPageTableVPN2.CanFocus = true;
			this.entPageTableVPN2.Name = "entPageTableVPN2";
			this.entPageTableVPN2.IsEditable = false;
			this.entPageTableVPN2.InvisibleChar = '●';
			this.table1.Add(this.entPageTableVPN2);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTableVPN2]));
			w27.TopAttach = ((uint)(3));
			w27.BottomAttach = ((uint)(4));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entPageTableVPN3 = new global::Gtk.Entry();
			this.entPageTableVPN3.CanFocus = true;
			this.entPageTableVPN3.Name = "entPageTableVPN3";
			this.entPageTableVPN3.IsEditable = false;
			this.entPageTableVPN3.InvisibleChar = '●';
			this.table1.Add(this.entPageTableVPN3);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1[this.entPageTableVPN3]));
			w28.TopAttach = ((uint)(4));
			w28.BottomAttach = ((uint)(5));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("VPN");
			this.table1.Add(this.label25);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1[this.label25]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("PFN");
			this.table1.Add(this.label26);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1[this.label26]));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add(this.table1);
			this.frame5.Add(this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Page Table</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel3;
			this.fixed1.Add(this.frame5);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame5]));
			w33.X = 112;
			w33.Y = 204;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vWirePFN = new global::VisualizerComponents.VWireWidget();
			this.vWirePFN.WidthRequest = 3;
			this.vWirePFN.HeightRequest = 107;
			this.vWirePFN.Events = ((global::Gdk.EventMask)(256));
			this.vWirePFN.Name = "vWirePFN";
			this.vWirePFN.Identifier = "state0";
			this.fixed1.Add(this.vWirePFN);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vWirePFN]));
			w34.X = 357;
			w34.Y = 103;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hWirePFN1 = new global::VisualizerComponents.HWireWidget();
			this.hWirePFN1.WidthRequest = 40;
			this.hWirePFN1.HeightRequest = 3;
			this.hWirePFN1.Events = ((global::Gdk.EventMask)(256));
			this.hWirePFN1.Name = "hWirePFN1";
			this.hWirePFN1.Identifier = "state0";
			this.fixed1.Add(this.hWirePFN1);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hWirePFN1]));
			w35.X = 360;
			w35.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hWirePFN2 = new global::VisualizerComponents.HWireWidget();
			this.hWirePFN2.WidthRequest = 80;
			this.hWirePFN2.HeightRequest = 3;
			this.hWirePFN2.Events = ((global::Gdk.EventMask)(256));
			this.hWirePFN2.Name = "hWirePFN2";
			this.hWirePFN2.Identifier = "step1";
			this.fixed1.Add(this.hWirePFN2);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hWirePFN2]));
			w36.X = 594;
			w36.Y = 157;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hWireOffset2 = new global::VisualizerComponents.HWireWidget();
			this.hWireOffset2.WidthRequest = 109;
			this.hWireOffset2.HeightRequest = 3;
			this.hWireOffset2.Events = ((global::Gdk.EventMask)(256));
			this.hWireOffset2.Name = "hWireOffset2";
			this.hWireOffset2.Identifier = "step1";
			this.fixed1.Add(this.hWireOffset2);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hWireOffset2]));
			w37.X = 594;
			w37.Y = 101;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vWireVPN = new global::VisualizerComponents.VWireWidget();
			this.vWireVPN.WidthRequest = 3;
			this.vWireVPN.HeightRequest = 209;
			this.vWireVPN.Events = ((global::Gdk.EventMask)(256));
			this.vWireVPN.Name = "vWireVPN";
			this.vWireVPN.Identifier = "state0-0";
			this.fixed1.Add(this.vWireVPN);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vWireVPN]));
			w38.X = 14;
			w38.Y = 104;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hwirewidget1 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget1.WidthRequest = 14;
			this.hwirewidget1.HeightRequest = 3;
			this.hwirewidget1.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget1.Name = "hwirewidget1";
			this.hwirewidget1.Identifier = "state0-0";
			this.fixed1.Add(this.hwirewidget1);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hwirewidget1]));
			w39.X = 13;
			w39.Y = 99;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			// Container child frame3.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.WidthRequest = 260;
			this.scrolledwindow1.HeightRequest = 350;
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w40 = new global::Gtk.Viewport();
			w40.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table(((uint)(17)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem = new global::Gtk.Entry();
			this.entPhysMem.CanFocus = true;
			this.entPhysMem.Name = "entPhysMem";
			this.entPhysMem.Text = global::Mono.Unix.Catalog.GetString("xDEADBEEF");
			this.entPhysMem.IsEditable = false;
			this.entPhysMem.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem]));
			w41.TopAttach = ((uint)(1));
			w41.BottomAttach = ((uint)(2));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem1 = new global::Gtk.Entry();
			this.entPhysMem1.CanFocus = true;
			this.entPhysMem1.Name = "entPhysMem1";
			this.entPhysMem1.IsEditable = false;
			this.entPhysMem1.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem1);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem1]));
			w42.TopAttach = ((uint)(2));
			w42.BottomAttach = ((uint)(3));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem10 = new global::Gtk.Entry();
			this.entPhysMem10.CanFocus = true;
			this.entPhysMem10.Name = "entPhysMem10";
			this.entPhysMem10.IsEditable = false;
			this.entPhysMem10.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem10);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem10]));
			w43.TopAttach = ((uint)(11));
			w43.BottomAttach = ((uint)(12));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem11 = new global::Gtk.Entry();
			this.entPhysMem11.CanFocus = true;
			this.entPhysMem11.Name = "entPhysMem11";
			this.entPhysMem11.IsEditable = false;
			this.entPhysMem11.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem11);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem11]));
			w44.TopAttach = ((uint)(12));
			w44.BottomAttach = ((uint)(13));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem12 = new global::Gtk.Entry();
			this.entPhysMem12.CanFocus = true;
			this.entPhysMem12.Name = "entPhysMem12";
			this.entPhysMem12.IsEditable = false;
			this.entPhysMem12.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem12);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem12]));
			w45.TopAttach = ((uint)(13));
			w45.BottomAttach = ((uint)(14));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem13 = new global::Gtk.Entry();
			this.entPhysMem13.CanFocus = true;
			this.entPhysMem13.Name = "entPhysMem13";
			this.entPhysMem13.IsEditable = false;
			this.entPhysMem13.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem13);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem13]));
			w46.TopAttach = ((uint)(14));
			w46.BottomAttach = ((uint)(15));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem14 = new global::Gtk.Entry();
			this.entPhysMem14.CanFocus = true;
			this.entPhysMem14.Name = "entPhysMem14";
			this.entPhysMem14.IsEditable = false;
			this.entPhysMem14.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem14);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem14]));
			w47.TopAttach = ((uint)(15));
			w47.BottomAttach = ((uint)(16));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem15 = new global::Gtk.Entry();
			this.entPhysMem15.CanFocus = true;
			this.entPhysMem15.Name = "entPhysMem15";
			this.entPhysMem15.IsEditable = false;
			this.entPhysMem15.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem15);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem15]));
			w48.TopAttach = ((uint)(16));
			w48.BottomAttach = ((uint)(17));
			w48.LeftAttach = ((uint)(1));
			w48.RightAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem2 = new global::Gtk.Entry();
			this.entPhysMem2.CanFocus = true;
			this.entPhysMem2.Name = "entPhysMem2";
			this.entPhysMem2.IsEditable = false;
			this.entPhysMem2.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem2);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem2]));
			w49.TopAttach = ((uint)(3));
			w49.BottomAttach = ((uint)(4));
			w49.LeftAttach = ((uint)(1));
			w49.RightAttach = ((uint)(2));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem3 = new global::Gtk.Entry();
			this.entPhysMem3.CanFocus = true;
			this.entPhysMem3.Name = "entPhysMem3";
			this.entPhysMem3.IsEditable = false;
			this.entPhysMem3.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem3);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem3]));
			w50.TopAttach = ((uint)(4));
			w50.BottomAttach = ((uint)(5));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem4 = new global::Gtk.Entry();
			this.entPhysMem4.CanFocus = true;
			this.entPhysMem4.Name = "entPhysMem4";
			this.entPhysMem4.IsEditable = false;
			this.entPhysMem4.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem4);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem4]));
			w51.TopAttach = ((uint)(5));
			w51.BottomAttach = ((uint)(6));
			w51.LeftAttach = ((uint)(1));
			w51.RightAttach = ((uint)(2));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem5 = new global::Gtk.Entry();
			this.entPhysMem5.CanFocus = true;
			this.entPhysMem5.Name = "entPhysMem5";
			this.entPhysMem5.IsEditable = false;
			this.entPhysMem5.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem5);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem5]));
			w52.TopAttach = ((uint)(6));
			w52.BottomAttach = ((uint)(7));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem6 = new global::Gtk.Entry();
			this.entPhysMem6.CanFocus = true;
			this.entPhysMem6.Name = "entPhysMem6";
			this.entPhysMem6.IsEditable = false;
			this.entPhysMem6.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem6);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem6]));
			w53.TopAttach = ((uint)(7));
			w53.BottomAttach = ((uint)(8));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem7 = new global::Gtk.Entry();
			this.entPhysMem7.CanFocus = true;
			this.entPhysMem7.Name = "entPhysMem7";
			this.entPhysMem7.IsEditable = false;
			this.entPhysMem7.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem7);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem7]));
			w54.TopAttach = ((uint)(8));
			w54.BottomAttach = ((uint)(9));
			w54.LeftAttach = ((uint)(1));
			w54.RightAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem8 = new global::Gtk.Entry();
			this.entPhysMem8.CanFocus = true;
			this.entPhysMem8.Name = "entPhysMem8";
			this.entPhysMem8.IsEditable = false;
			this.entPhysMem8.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem8);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem8]));
			w55.TopAttach = ((uint)(9));
			w55.BottomAttach = ((uint)(10));
			w55.LeftAttach = ((uint)(1));
			w55.RightAttach = ((uint)(2));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entPhysMem9 = new global::Gtk.Entry();
			this.entPhysMem9.CanFocus = true;
			this.entPhysMem9.Name = "entPhysMem9";
			this.entPhysMem9.IsEditable = false;
			this.entPhysMem9.InvisibleChar = '●';
			this.table2.Add(this.entPhysMem9);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table2[this.entPhysMem9]));
			w56.TopAttach = ((uint)(10));
			w56.BottomAttach = ((uint)(11));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("0110   6");
			this.table2.Add(this.label10);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table2[this.label10]));
			w57.TopAttach = ((uint)(7));
			w57.BottomAttach = ((uint)(8));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("0111   7");
			this.table2.Add(this.label11);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table2[this.label11]));
			w58.TopAttach = ((uint)(8));
			w58.BottomAttach = ((uint)(9));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("1000   8");
			this.table2.Add(this.label12);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table2[this.label12]));
			w59.TopAttach = ((uint)(9));
			w59.BottomAttach = ((uint)(10));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("1001   9");
			this.table2.Add(this.label13);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table2[this.label13]));
			w60.TopAttach = ((uint)(10));
			w60.BottomAttach = ((uint)(11));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("1010  10");
			this.table2.Add(this.label14);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table2[this.label14]));
			w61.TopAttach = ((uint)(11));
			w61.BottomAttach = ((uint)(12));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("1011  11");
			this.table2.Add(this.label15);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table2[this.label15]));
			w62.TopAttach = ((uint)(12));
			w62.BottomAttach = ((uint)(13));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("1100  12");
			this.table2.Add(this.label16);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table2[this.label16]));
			w63.TopAttach = ((uint)(13));
			w63.BottomAttach = ((uint)(14));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("1101  13");
			this.table2.Add(this.label17);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table2[this.label17]));
			w64.TopAttach = ((uint)(14));
			w64.BottomAttach = ((uint)(15));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("1110  14");
			this.table2.Add(this.label18);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table2[this.label18]));
			w65.TopAttach = ((uint)(15));
			w65.BottomAttach = ((uint)(16));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("1111  15");
			this.table2.Add(this.label19);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table2[this.label19]));
			w66.TopAttach = ((uint)(16));
			w66.BottomAttach = ((uint)(17));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Address");
			this.table2.Add(this.label20);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table2[this.label20]));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Value");
			this.table2.Add(this.label29);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table2[this.label29]));
			w68.LeftAttach = ((uint)(1));
			w68.RightAttach = ((uint)(2));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.table2.Add(this.label30);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table2[this.label30]));
			w69.TopAttach = ((uint)(1));
			w69.BottomAttach = ((uint)(2));
			w69.LeftAttach = ((uint)(2));
			w69.RightAttach = ((uint)(3));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("1");
			this.table2.Add(this.label31);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table2[this.label31]));
			w70.TopAttach = ((uint)(5));
			w70.BottomAttach = ((uint)(6));
			w70.LeftAttach = ((uint)(2));
			w70.RightAttach = ((uint)(3));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("2");
			this.table2.Add(this.label32);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table2[this.label32]));
			w71.TopAttach = ((uint)(9));
			w71.BottomAttach = ((uint)(10));
			w71.LeftAttach = ((uint)(2));
			w71.RightAttach = ((uint)(3));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label33 = new global::Gtk.Label();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("3");
			this.table2.Add(this.label33);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table2[this.label33]));
			w72.TopAttach = ((uint)(13));
			w72.BottomAttach = ((uint)(14));
			w72.LeftAttach = ((uint)(2));
			w72.RightAttach = ((uint)(3));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label38 = new global::Gtk.Label();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("PFN");
			this.table2.Add(this.label38);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table2[this.label38]));
			w73.LeftAttach = ((uint)(2));
			w73.RightAttach = ((uint)(3));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("0000   0");
			this.table2.Add(this.label4);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table2[this.label4]));
			w74.TopAttach = ((uint)(1));
			w74.BottomAttach = ((uint)(2));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label40 = new global::Gtk.Label();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.table2.Add(this.label40);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table2[this.label40]));
			w75.TopAttach = ((uint)(2));
			w75.BottomAttach = ((uint)(3));
			w75.LeftAttach = ((uint)(2));
			w75.RightAttach = ((uint)(3));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label41 = new global::Gtk.Label();
			this.label41.Name = "label41";
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.table2.Add(this.label41);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table2[this.label41]));
			w76.TopAttach = ((uint)(3));
			w76.BottomAttach = ((uint)(4));
			w76.LeftAttach = ((uint)(2));
			w76.RightAttach = ((uint)(3));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label42 = new global::Gtk.Label();
			this.label42.Name = "label42";
			this.label42.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.table2.Add(this.label42);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table2[this.label42]));
			w77.TopAttach = ((uint)(4));
			w77.BottomAttach = ((uint)(5));
			w77.LeftAttach = ((uint)(2));
			w77.RightAttach = ((uint)(3));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label43 = new global::Gtk.Label();
			this.label43.Name = "label43";
			this.label43.LabelProp = global::Mono.Unix.Catalog.GetString("1");
			this.table2.Add(this.label43);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table2[this.label43]));
			w78.TopAttach = ((uint)(6));
			w78.BottomAttach = ((uint)(7));
			w78.LeftAttach = ((uint)(2));
			w78.RightAttach = ((uint)(3));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label44 = new global::Gtk.Label();
			this.label44.Name = "label44";
			this.label44.LabelProp = global::Mono.Unix.Catalog.GetString("1");
			this.table2.Add(this.label44);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table2[this.label44]));
			w79.TopAttach = ((uint)(7));
			w79.BottomAttach = ((uint)(8));
			w79.LeftAttach = ((uint)(2));
			w79.RightAttach = ((uint)(3));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label45 = new global::Gtk.Label();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("1");
			this.table2.Add(this.label45);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table2[this.label45]));
			w80.TopAttach = ((uint)(8));
			w80.BottomAttach = ((uint)(9));
			w80.LeftAttach = ((uint)(2));
			w80.RightAttach = ((uint)(3));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label46 = new global::Gtk.Label();
			this.label46.Name = "label46";
			this.label46.LabelProp = global::Mono.Unix.Catalog.GetString("2");
			this.table2.Add(this.label46);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table2[this.label46]));
			w81.TopAttach = ((uint)(10));
			w81.BottomAttach = ((uint)(11));
			w81.LeftAttach = ((uint)(2));
			w81.RightAttach = ((uint)(3));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label47 = new global::Gtk.Label();
			this.label47.Name = "label47";
			this.label47.LabelProp = global::Mono.Unix.Catalog.GetString("2");
			this.table2.Add(this.label47);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table2[this.label47]));
			w82.TopAttach = ((uint)(11));
			w82.BottomAttach = ((uint)(12));
			w82.LeftAttach = ((uint)(2));
			w82.RightAttach = ((uint)(3));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label48 = new global::Gtk.Label();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString("2");
			this.table2.Add(this.label48);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table2[this.label48]));
			w83.TopAttach = ((uint)(12));
			w83.BottomAttach = ((uint)(13));
			w83.LeftAttach = ((uint)(2));
			w83.RightAttach = ((uint)(3));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label49 = new global::Gtk.Label();
			this.label49.Name = "label49";
			this.label49.LabelProp = global::Mono.Unix.Catalog.GetString("3");
			this.table2.Add(this.label49);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table2[this.label49]));
			w84.TopAttach = ((uint)(14));
			w84.BottomAttach = ((uint)(15));
			w84.LeftAttach = ((uint)(2));
			w84.RightAttach = ((uint)(3));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("0001   1");
			this.table2.Add(this.label5);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table2[this.label5]));
			w85.TopAttach = ((uint)(2));
			w85.BottomAttach = ((uint)(3));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label50 = new global::Gtk.Label();
			this.label50.Name = "label50";
			this.label50.LabelProp = global::Mono.Unix.Catalog.GetString("3");
			this.table2.Add(this.label50);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table2[this.label50]));
			w86.TopAttach = ((uint)(15));
			w86.BottomAttach = ((uint)(16));
			w86.LeftAttach = ((uint)(2));
			w86.RightAttach = ((uint)(3));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label51 = new global::Gtk.Label();
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString("3");
			this.table2.Add(this.label51);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table2[this.label51]));
			w87.TopAttach = ((uint)(16));
			w87.BottomAttach = ((uint)(17));
			w87.LeftAttach = ((uint)(2));
			w87.RightAttach = ((uint)(3));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("0010   2");
			this.table2.Add(this.label6);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table2[this.label6]));
			w88.TopAttach = ((uint)(3));
			w88.BottomAttach = ((uint)(4));
			w88.XOptions = ((global::Gtk.AttachOptions)(4));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("0011   3");
			this.table2.Add(this.label7);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table2[this.label7]));
			w89.TopAttach = ((uint)(4));
			w89.BottomAttach = ((uint)(5));
			w89.XOptions = ((global::Gtk.AttachOptions)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("0100   4");
			this.table2.Add(this.label8);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table2[this.label8]));
			w90.TopAttach = ((uint)(5));
			w90.BottomAttach = ((uint)(6));
			w90.XOptions = ((global::Gtk.AttachOptions)(4));
			w90.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("0101   5");
			this.table2.Add(this.label9);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table2[this.label9]));
			w91.TopAttach = ((uint)(6));
			w91.BottomAttach = ((uint)(7));
			w91.XOptions = ((global::Gtk.AttachOptions)(4));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add(this.table2);
			w40.Add(this.GtkAlignment1);
			this.scrolledwindow1.Add(w40);
			this.frame3.Add(this.scrolledwindow1);
			this.GtkLabel1 = new global::Gtk.Label();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Physical Memory</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel1;
			this.fixed1.Add(this.frame3);
			global::Gtk.Fixed.FixedChild w96 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame3]));
			w96.X = 656;
			w96.Y = 28;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.entMemoryAccessResult = new global::Gtk.Entry();
			this.entMemoryAccessResult.CanFocus = true;
			this.entMemoryAccessResult.Name = "entMemoryAccessResult";
			this.entMemoryAccessResult.IsEditable = true;
			this.entMemoryAccessResult.InvisibleChar = '●';
			this.GtkAlignment4.Add(this.entMemoryAccessResult);
			this.frame6.Add(this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Memory Access Result</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel4;
			this.fixed1.Add(this.frame6);
			global::Gtk.Fixed.FixedChild w99 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame6]));
			w99.X = 946;
			w99.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vWirePhysMemValue = new global::VisualizerComponents.VWireWidget();
			this.vWirePhysMemValue.WidthRequest = 3;
			this.vWirePhysMemValue.HeightRequest = 120;
			this.vWirePhysMemValue.Events = ((global::Gdk.EventMask)(256));
			this.vWirePhysMemValue.Name = "vWirePhysMemValue";
			this.vWirePhysMemValue.Identifier = "step1";
			this.fixed1.Add(this.vWirePhysMemValue);
			global::Gtk.Fixed.FixedChild w100 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vWirePhysMemValue]));
			w100.X = 1017;
			w100.Y = 106;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hWirePhysMemValue = new global::VisualizerComponents.HWireWidget();
			this.hWirePhysMemValue.WidthRequest = 98;
			this.hWirePhysMemValue.HeightRequest = 3;
			this.hWirePhysMemValue.Events = ((global::Gdk.EventMask)(256));
			this.hWirePhysMemValue.Name = "hWirePhysMemValue";
			this.hWirePhysMemValue.Identifier = "step1";
			this.fixed1.Add(this.hWirePhysMemValue);
			global::Gtk.Fixed.FixedChild w101 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hWirePhysMemValue]));
			w101.X = 920;
			w101.Y = 226;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
