
// This file has been generated by the GUI designer. Do not modify.
namespace DummyVisualizer
{
	public partial class DummyVisualizer
	{
		private global::Gtk.Fixed fixed4;

		private global::VisualizerComponents.MemoryItemWidget addr_step1_memoryitemwidget;

		private global::VisualizerComponents.MemoryItemWidget putWhere_step1_memoryitemwidget;

		private global::VisualizerComponents.MemoryItemWidget addr_step2_memoryitemwidget;

		private global::VisualizerComponents.MemoryItemWidget putWhere_step2_memoryitemwidget;

		private global::VisualizerComponents.MemoryItemWidget addr_init_memoryitemwidget;

		private global::VisualizerComponents.MemoryItemWidget putWhere_value_memoryitemwidget;

		private global::VisualizerComponents.VWireWidget vwirewidget2;

		private global::VisualizerComponents.HWireWidget hwirewidget2;

		private global::VisualizerComponents.MemoryItemWidget read_write_memoryitemwidget;

		private global::VisualizerComponents.HWireWidget hwirewidget4;

		private global::VisualizerComponents.HWireWidget hwirewidget3;

		private global::VisualizerComponents.HWireWidget hwirewidget1;

		private global::VisualizerComponents.VWireWidget vwirewidget1;

		private global::VisualizerComponents.HWireWidget hwirewidget5;

		private global::VisualizerComponents.VWireWidget vwirewidget3;

		private global::VisualizerComponents.VWireWidget vwirewidget4;

		private global::VisualizerComponents.HWireWidget hwirewidget6;

		private global::VisualizerComponents.HWireWidget hwirewidget7;

		private global::VisualizerComponents.VWireWidget vwirewidget5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DummyVisualizer.DummyVisualizer
			global::Stetic.BinContainer.Attach(this);
			this.Name = "DummyVisualizer.DummyVisualizer";
			// Container child DummyVisualizer.DummyVisualizer.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.addr_step1_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.addr_step1_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.addr_step1_memoryitemwidget.Name = "addr_step1_memoryitemwidget";
			this.addr_step1_memoryitemwidget.LabelText = "Step 1";
			this.addr_step1_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.addr_step1_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.addr_step1_memoryitemwidget]));
			w1.X = 279;
			w1.Y = 32;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.putWhere_step1_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.putWhere_step1_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.putWhere_step1_memoryitemwidget.Name = "putWhere_step1_memoryitemwidget";
			this.putWhere_step1_memoryitemwidget.LabelText = "Step 1";
			this.putWhere_step1_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.putWhere_step1_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.putWhere_step1_memoryitemwidget]));
			w2.X = 279;
			w2.Y = 103;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.addr_step2_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.addr_step2_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.addr_step2_memoryitemwidget.Name = "addr_step2_memoryitemwidget";
			this.addr_step2_memoryitemwidget.LabelText = "Step 2";
			this.addr_step2_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.addr_step2_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.addr_step2_memoryitemwidget]));
			w3.X = 503;
			w3.Y = 33;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.putWhere_step2_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.putWhere_step2_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.putWhere_step2_memoryitemwidget.Name = "putWhere_step2_memoryitemwidget";
			this.putWhere_step2_memoryitemwidget.LabelText = "Step 2";
			this.putWhere_step2_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.putWhere_step2_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.putWhere_step2_memoryitemwidget]));
			w4.X = 505;
			w4.Y = 107;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.addr_init_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.addr_init_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.addr_init_memoryitemwidget.Name = "addr_init_memoryitemwidget";
			this.addr_init_memoryitemwidget.LabelText = "Address";
			this.addr_init_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.addr_init_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.addr_init_memoryitemwidget]));
			w5.X = 12;
			w5.Y = 40;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.putWhere_value_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.putWhere_value_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.putWhere_value_memoryitemwidget.Name = "putWhere_value_memoryitemwidget";
			this.putWhere_value_memoryitemwidget.LabelText = "";
			this.putWhere_value_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.putWhere_value_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.putWhere_value_memoryitemwidget]));
			w6.X = 11;
			w6.Y = 120;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.vwirewidget2 = new global::VisualizerComponents.VWireWidget();
			this.vwirewidget2.WidthRequest = 3;
			this.vwirewidget2.HeightRequest = 100;
			this.vwirewidget2.Events = ((global::Gdk.EventMask)(256));
			this.vwirewidget2.Name = "vwirewidget2";
			this.vwirewidget2.Identifier = "step-1";
			this.fixed4.Add(this.vwirewidget2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vwirewidget2]));
			w7.X = 79;
			w7.Y = 189;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget2 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget2.WidthRequest = 100;
			this.hwirewidget2.HeightRequest = 3;
			this.hwirewidget2.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget2.Name = "hwirewidget2";
			this.hwirewidget2.Identifier = "step-1";
			this.fixed4.Add(this.hwirewidget2);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget2]));
			w8.X = 79;
			w8.Y = 289;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.read_write_memoryitemwidget = new global::VisualizerComponents.MemoryItemWidget();
			this.read_write_memoryitemwidget.Events = ((global::Gdk.EventMask)(256));
			this.read_write_memoryitemwidget.Name = "read_write_memoryitemwidget";
			this.read_write_memoryitemwidget.LabelText = "Read/Write";
			this.read_write_memoryitemwidget.DataTextUserEditable = false;
			this.fixed4.Add(this.read_write_memoryitemwidget);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.read_write_memoryitemwidget]));
			w9.X = 184;
			w9.Y = 253;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget4 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget4.WidthRequest = 50;
			this.hwirewidget4.HeightRequest = 3;
			this.hwirewidget4.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget4.Name = "hwirewidget4";
			this.hwirewidget4.Identifier = "step1";
			this.fixed4.Add(this.hwirewidget4);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget4]));
			w10.X = 449;
			w10.Y = 70;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget3 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget3.WidthRequest = 93;
			this.hwirewidget3.HeightRequest = 3;
			this.hwirewidget3.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget3.Name = "hwirewidget3";
			this.hwirewidget3.Identifier = "step0";
			this.fixed4.Add(this.hwirewidget3);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget3]));
			w11.X = 181;
			w11.Y = 147;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget1 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget1.WidthRequest = 88;
			this.hwirewidget1.HeightRequest = 3;
			this.hwirewidget1.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget1.Name = "hwirewidget1";
			this.hwirewidget1.Identifier = "step0";
			this.fixed4.Add(this.hwirewidget1);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget1]));
			w12.X = 184;
			w12.Y = 73;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.vwirewidget1 = new global::VisualizerComponents.VWireWidget();
			this.vwirewidget1.WidthRequest = 3;
			this.vwirewidget1.HeightRequest = 100;
			this.vwirewidget1.Events = ((global::Gdk.EventMask)(256));
			this.vwirewidget1.Name = "vwirewidget1";
			this.vwirewidget1.Identifier = "step1";
			this.fixed4.Add(this.vwirewidget1);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vwirewidget1]));
			w13.X = 372;
			w13.Y = 170;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget5 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget5.WidthRequest = 100;
			this.hwirewidget5.HeightRequest = 3;
			this.hwirewidget5.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget5.Name = "hwirewidget5";
			this.hwirewidget5.Identifier = "step1";
			this.fixed4.Add(this.hwirewidget5);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget5]));
			w14.X = 370;
			w14.Y = 267;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.vwirewidget3 = new global::VisualizerComponents.VWireWidget();
			this.vwirewidget3.WidthRequest = 3;
			this.vwirewidget3.HeightRequest = 25;
			this.vwirewidget3.Events = ((global::Gdk.EventMask)(256));
			this.vwirewidget3.Name = "vwirewidget3";
			this.vwirewidget3.Identifier = "step1";
			this.fixed4.Add(this.vwirewidget3);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vwirewidget3]));
			w15.X = 467;
			w15.Y = 244;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.vwirewidget4 = new global::VisualizerComponents.VWireWidget();
			this.vwirewidget4.WidthRequest = 3;
			this.vwirewidget4.HeightRequest = 25;
			this.vwirewidget4.Events = ((global::Gdk.EventMask)(256));
			this.vwirewidget4.Name = "vwirewidget4";
			this.vwirewidget4.Identifier = "step1";
			this.fixed4.Add(this.vwirewidget4);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vwirewidget4]));
			w16.X = 492;
			w16.Y = 245;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget6 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget6.WidthRequest = 26;
			this.hwirewidget6.HeightRequest = 3;
			this.hwirewidget6.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget6.Name = "hwirewidget6";
			this.hwirewidget6.Identifier = "step1";
			this.fixed4.Add(this.hwirewidget6);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget6]));
			w17.X = 468;
			w17.Y = 244;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.hwirewidget7 = new global::VisualizerComponents.HWireWidget();
			this.hwirewidget7.WidthRequest = 96;
			this.hwirewidget7.HeightRequest = 3;
			this.hwirewidget7.Events = ((global::Gdk.EventMask)(256));
			this.hwirewidget7.Name = "hwirewidget7";
			this.hwirewidget7.Identifier = "step1";
			this.fixed4.Add(this.hwirewidget7);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hwirewidget7]));
			w18.X = 493;
			w18.Y = 268;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.vwirewidget5 = new global::VisualizerComponents.VWireWidget();
			this.vwirewidget5.WidthRequest = 3;
			this.vwirewidget5.HeightRequest = 94;
			this.vwirewidget5.Events = ((global::Gdk.EventMask)(256));
			this.vwirewidget5.Name = "vwirewidget5";
			this.vwirewidget5.Identifier = "step1";
			this.fixed4.Add(this.vwirewidget5);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vwirewidget5]));
			w19.X = 588;
			w19.Y = 177;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
