
// This file has been generated by the GUI designer. Do not modify.
namespace DirectMappedCacheVisualizer
{
	public partial class DirectMappedCacheVisualizer
	{
		private global::Gtk.Fixed fixed1;

		private global::VisualizerComponents.MemoryItemWidget tag_widget;

		private global::VisualizerComponents.MemoryItemWidget index_widget;

		private global::VisualizerComponents.MemoryItemWidget memory_address_widget;

		private global::Gtk.Table table1;

		private global::Gtk.Entry data0_entry;

		private global::Gtk.Entry data1_entry;

		private global::Gtk.Entry data2_entry;

		private global::Gtk.Entry data3_entry;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry tag0_entry;

		private global::Gtk.Entry tag1_entry;

		private global::Gtk.Entry tag2_entry;

		private global::Gtk.Entry tag3_entry;

		private global::Gtk.Entry valid0_entry;

		private global::Gtk.Entry valid1_entry;

		private global::Gtk.Entry valid2_entry;

		private global::Gtk.Entry valid3_entry;

		private global::VisualizerComponents.MemoryItemWidget tagEqual_widget;

		private global::VisualizerComponents.MemoryItemWidget cacheHit_widget;

		private global::VisualizerComponents.MemoryItemWidget cacheData_widget;

		private global::Gtk.Image image187;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DirectMappedCacheVisualizer.DirectMappedCacheVisualizer
			global::Stetic.BinContainer.Attach(this);
			this.Name = "DirectMappedCacheVisualizer.DirectMappedCacheVisualizer";
			// Container child DirectMappedCacheVisualizer.DirectMappedCacheVisualizer.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tag_widget = new global::VisualizerComponents.MemoryItemWidget();
			this.tag_widget.Events = ((global::Gdk.EventMask)(256));
			this.tag_widget.Name = "tag_widget";
			this.tag_widget.LabelText = "Tag";
			this.tag_widget.DataTextUserEditable = false;
			this.fixed1.Add(this.tag_widget);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tag_widget]));
			w1.X = 16;
			w1.Y = 99;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.index_widget = new global::VisualizerComponents.MemoryItemWidget();
			this.index_widget.Events = ((global::Gdk.EventMask)(256));
			this.index_widget.Name = "index_widget";
			this.index_widget.LabelText = "Index";
			this.index_widget.DataTextUserEditable = false;
			this.fixed1.Add(this.index_widget);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.index_widget]));
			w2.X = 196;
			w2.Y = 98;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.memory_address_widget = new global::VisualizerComponents.MemoryItemWidget();
			this.memory_address_widget.Events = ((global::Gdk.EventMask)(256));
			this.memory_address_widget.Name = "memory_address_widget";
			this.memory_address_widget.LabelText = "Mem Address";
			this.memory_address_widget.DataTextUserEditable = false;
			this.fixed1.Add(this.memory_address_widget);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.memory_address_widget]));
			w3.X = 105;
			w3.Y = 23;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.data0_entry = new global::Gtk.Entry();
			this.data0_entry.CanFocus = true;
			this.data0_entry.Name = "data0_entry";
			this.data0_entry.IsEditable = true;
			this.data0_entry.InvisibleChar = '●';
			this.table1.Add(this.data0_entry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.data0_entry]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.data1_entry = new global::Gtk.Entry();
			this.data1_entry.CanFocus = true;
			this.data1_entry.Name = "data1_entry";
			this.data1_entry.IsEditable = true;
			this.data1_entry.InvisibleChar = '●';
			this.table1.Add(this.data1_entry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.data1_entry]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.data2_entry = new global::Gtk.Entry();
			this.data2_entry.CanFocus = true;
			this.data2_entry.Name = "data2_entry";
			this.data2_entry.IsEditable = true;
			this.data2_entry.InvisibleChar = '●';
			this.table1.Add(this.data2_entry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.data2_entry]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.data3_entry = new global::Gtk.Entry();
			this.data3_entry.CanFocus = true;
			this.data3_entry.Name = "data3_entry";
			this.data3_entry.IsEditable = true;
			this.data3_entry.InvisibleChar = '●';
			this.table1.Add(this.data3_entry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.data3_entry]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 40;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Valid");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Tag");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Data");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tag0_entry = new global::Gtk.Entry();
			this.tag0_entry.CanFocus = true;
			this.tag0_entry.Name = "tag0_entry";
			this.tag0_entry.IsEditable = true;
			this.tag0_entry.InvisibleChar = '●';
			this.table1.Add(this.tag0_entry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.tag0_entry]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tag1_entry = new global::Gtk.Entry();
			this.tag1_entry.CanFocus = true;
			this.tag1_entry.Name = "tag1_entry";
			this.tag1_entry.IsEditable = true;
			this.tag1_entry.InvisibleChar = '●';
			this.table1.Add(this.tag1_entry);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.tag1_entry]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tag2_entry = new global::Gtk.Entry();
			this.tag2_entry.CanFocus = true;
			this.tag2_entry.Name = "tag2_entry";
			this.tag2_entry.IsEditable = true;
			this.tag2_entry.InvisibleChar = '●';
			this.table1.Add(this.tag2_entry);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.tag2_entry]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tag3_entry = new global::Gtk.Entry();
			this.tag3_entry.CanFocus = true;
			this.tag3_entry.Name = "tag3_entry";
			this.tag3_entry.IsEditable = true;
			this.tag3_entry.InvisibleChar = '●';
			this.table1.Add(this.tag3_entry);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.tag3_entry]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.valid0_entry = new global::Gtk.Entry();
			this.valid0_entry.WidthRequest = 40;
			this.valid0_entry.CanFocus = true;
			this.valid0_entry.Name = "valid0_entry";
			this.valid0_entry.IsEditable = true;
			this.valid0_entry.InvisibleChar = '●';
			this.table1.Add(this.valid0_entry);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.valid0_entry]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.valid1_entry = new global::Gtk.Entry();
			this.valid1_entry.WidthRequest = 40;
			this.valid1_entry.CanFocus = true;
			this.valid1_entry.Name = "valid1_entry";
			this.valid1_entry.IsEditable = true;
			this.valid1_entry.InvisibleChar = '●';
			this.table1.Add(this.valid1_entry);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.valid1_entry]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.valid2_entry = new global::Gtk.Entry();
			this.valid2_entry.WidthRequest = 40;
			this.valid2_entry.CanFocus = true;
			this.valid2_entry.Name = "valid2_entry";
			this.valid2_entry.IsEditable = true;
			this.valid2_entry.InvisibleChar = '●';
			this.table1.Add(this.valid2_entry);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.valid2_entry]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.valid3_entry = new global::Gtk.Entry();
			this.valid3_entry.WidthRequest = 40;
			this.valid3_entry.CanFocus = true;
			this.valid3_entry.Name = "valid3_entry";
			this.valid3_entry.IsEditable = true;
			this.valid3_entry.InvisibleChar = '●';
			this.table1.Add(this.valid3_entry);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.valid3_entry]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.fixed1.Add(this.table1);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.table1]));
			w19.X = 464;
			w19.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tagEqual_widget = new global::VisualizerComponents.MemoryItemWidget();
			this.tagEqual_widget.Events = ((global::Gdk.EventMask)(256));
			this.tagEqual_widget.Name = "tagEqual_widget";
			this.tagEqual_widget.LabelText = "Tag Equal?";
			this.tagEqual_widget.DataTextUserEditable = false;
			this.fixed1.Add(this.tagEqual_widget);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tagEqual_widget]));
			w20.X = 506;
			w20.Y = 249;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cacheHit_widget = new global::VisualizerComponents.MemoryItemWidget();
			this.cacheHit_widget.Events = ((global::Gdk.EventMask)(256));
			this.cacheHit_widget.Name = "cacheHit_widget";
			this.cacheHit_widget.LabelText = "Cache Hit";
			this.cacheHit_widget.DataTextUserEditable = false;
			this.fixed1.Add(this.cacheHit_widget);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cacheHit_widget]));
			w21.X = 503;
			w21.Y = 347;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cacheData_widget = new global::VisualizerComponents.MemoryItemWidget();
			this.cacheData_widget.Events = ((global::Gdk.EventMask)(256));
			this.cacheData_widget.Name = "cacheData_widget";
			this.cacheData_widget.LabelText = "Data";
			this.cacheData_widget.DataTextUserEditable = false;
			this.fixed1.Add(this.cacheData_widget);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cacheData_widget]));
			w22.X = 675;
			w22.Y = 348;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image187 = new global::Gtk.Image();
			this.image187.Name = "image187";
			this.image187.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DirectMappedCacheVisualizer.2016-09-28 03_33_24-Memory Visualizer.png");
			this.fixed1.Add(this.image187);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image187]));
			w23.Y = -59;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
