
// This file has been generated by the GUI designer. Do not modify.
namespace VisualizerComponents
{
	public partial class VWireWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget VisualizerComponents.VWireWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 3;
			this.HeightRequest = 100;
			this.Name = "VisualizerComponents.VWireWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
