
// This file has been generated by the GUI designer. Do not modify.
namespace VisualizerComponents
{
	public partial class MemoryItemWidget
	{
		private global::Gtk.Frame Frame;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox VBox;
		
		private global::Gtk.Label Label;
		
		private global::Gtk.Entry Entry;
		
		private global::Gtk.Label GtkLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VisualizerComponents.MemoryItemWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VisualizerComponents.MemoryItemWidget";
			// Container child VisualizerComponents.MemoryItemWidget.Gtk.Container+ContainerChild
			this.Frame = new global::Gtk.Frame ();
			this.Frame.Name = "Frame";
			// Container child Frame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.VBox = new global::Gtk.VBox ();
			this.VBox.Name = "VBox";
			this.VBox.Spacing = 6;
			// Container child VBox.Gtk.Box+BoxChild
			this.Label = new global::Gtk.Label ();
			this.Label.Name = "Label";
			this.Label.LabelProp = "MemoryItemWidget";
			this.VBox.Add (this.Label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.VBox [this.Label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child VBox.Gtk.Box+BoxChild
			this.Entry = new global::Gtk.Entry ();
			this.Entry.CanFocus = true;
			this.Entry.Name = "Entry";
			this.Entry.IsEditable = true;
			this.Entry.InvisibleChar = '●';
			this.VBox.Add (this.Entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.VBox [this.Entry]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.GtkAlignment.Add (this.VBox);
			this.Frame.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.UseMarkup = true;
			this.Frame.LabelWidget = this.GtkLabel;
			this.Add (this.Frame);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
