
// This file has been generated by the GUI designer. Do not modify.
namespace VisualizerComponents
{
	public partial class HWireWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget VisualizerComponents.HWireWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 100;
			this.HeightRequest = 3;
			this.Name = "VisualizerComponents.HWireWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
