
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action SimulationHelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox2;

	private global::Gtk.ComboBox visualizerSelector;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Label DescriptionBox;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button play;

	private global::Gtk.Button pause;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button reset;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button stepBack;

	private global::Gtk.Button stepForward;

	private global::Gtk.Entry commandLine_entry;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = "Exit";
		w1.Add(this.ExitAction, null);
		this.SimulationHelpAction = new global::Gtk.Action("SimulationHelpAction", global::Mono.Unix.Catalog.GetString("Simulation Help"), null, null);
		this.SimulationHelpAction.ShortLabel = "Simulation Help";
		w1.Add(this.SimulationHelpAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = "About";
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Memory Visualizer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='SimulationHelpAction' action='SimulationHelpAction'/><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.visualizerSelector = global::Gtk.ComboBox.NewText();
		this.visualizerSelector.Name = "visualizerSelector";
		this.hbox2.Add(this.visualizerSelector);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.visualizerSelector]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox4.Add(this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.vbox4.Add(this.fixed3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fixed3]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.DescriptionBox = new global::Gtk.Label();
		this.DescriptionBox.Name = "DescriptionBox";
		this.DescriptionBox.LabelProp = global::Mono.Unix.Catalog.GetString("INSERT TEXT HERE");
		this.vbox4.Add(this.DescriptionBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.DescriptionBox]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox2.Add(this.vbox4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
		w7.Position = 0;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.play = new global::Gtk.Button();
		global::Gtk.Tooltips w9 = new Gtk.Tooltips();
		w9.SetTip(this.play, "Play", "Play");
		this.play.CanFocus = true;
		this.play.Name = "play";
		this.play.UseUnderline = true;
		this.play.Label = global::Mono.Unix.Catalog.GetString("Play");
		global::Gtk.Image w10 = new global::Gtk.Image();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-play", global::Gtk.IconSize.Menu);
		this.play.Image = w10;
		this.hbox4.Add(this.play);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.play]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.pause = new global::Gtk.Button();
		w9.SetTip(this.pause, "Pause", "Pause");
		this.pause.CanFocus = true;
		this.pause.Name = "pause";
		this.pause.UseUnderline = true;
		this.pause.Label = global::Mono.Unix.Catalog.GetString("Pause");
		global::Gtk.Image w12 = new global::Gtk.Image();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-pause", global::Gtk.IconSize.Menu);
		this.pause.Image = w12;
		this.hbox4.Add(this.pause);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.pause]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.reset = new global::Gtk.Button();
		w9.SetTip(this.reset, "Reset", "Reset");
		this.reset.CanFocus = true;
		this.reset.Name = "reset";
		this.reset.UseUnderline = true;
		this.reset.Label = global::Mono.Unix.Catalog.GetString("Reset");
		global::Gtk.Image w14 = new global::Gtk.Image();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
		this.reset.Image = w14;
		this.hbox5.Add(this.reset);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.reset]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.stepBack = new global::Gtk.Button();
		w9.SetTip(this.stepBack, "Step Backward", "Step Backward");
		this.stepBack.CanFocus = true;
		this.stepBack.Name = "stepBack";
		this.stepBack.UseUnderline = true;
		this.stepBack.Label = global::Mono.Unix.Catalog.GetString("Step Backward");
		global::Gtk.Image w16 = new global::Gtk.Image();
		w16.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-previous", global::Gtk.IconSize.Menu);
		this.stepBack.Image = w16;
		this.hbox6.Add(this.stepBack);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.stepBack]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.stepForward = new global::Gtk.Button();
		w9.SetTip(this.stepForward, "Step Forward", "Step Forward");
		this.stepForward.CanFocus = true;
		this.stepForward.Name = "stepForward";
		this.stepForward.UseUnderline = true;
		this.stepForward.Label = global::Mono.Unix.Catalog.GetString("Step Forward");
		global::Gtk.Image w18 = new global::Gtk.Image();
		w18.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-next", global::Gtk.IconSize.Menu);
		this.stepForward.Image = w18;
		this.hbox6.Add(this.stepForward);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.stepForward]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox5.Add(this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.hbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.commandLine_entry = new global::Gtk.Entry();
		this.commandLine_entry.CanFocus = true;
		this.commandLine_entry.Name = "commandLine_entry";
		this.commandLine_entry.IsEditable = true;
		this.commandLine_entry.InvisibleChar = '●';
		this.vbox1.Add(this.commandLine_entry);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.commandLine_entry]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 868;
		this.DefaultHeight = 621;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler(this.onExit);
		this.SimulationHelpAction.Activated += new global::System.EventHandler(this.onSimHelp);
		this.AboutAction.Activated += new global::System.EventHandler(this.onAbout);
		this.visualizerSelector.Changed += new global::System.EventHandler(this.OnVisualizerSelectorChanged);
		this.reset.Clicked += new global::System.EventHandler(this.OnResetClicked);
		this.stepBack.Clicked += new global::System.EventHandler(this.OnStepBackClicked);
		this.stepForward.Clicked += new global::System.EventHandler(this.OnStepForwardClicked);
		this.commandLine_entry.Activated += new global::System.EventHandler(this.OnCommandLineEntryActivated);
	}
}
